### ISSUE TITLE
Form with single date question fails with TypeError

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo#957]
1. Go to http://xlsform.getodk.org (running Enketo v6.0.0-8-g4f65fcf)
2. Upload a form with single date question (or use [bug.xlsx](https://github.com/enketo/enketo-express/files/11030121/bug.xlsx))
3. Form converts, but returns `TypeError: this.$fakeDateI.datepicker is not a function` on preview.

Works on 6.0.0.
